### ISSUE TITLE
multiple button press to get one output

### ISSUE THREAD

**Issue by NerdsCorp** [atctwo/bbrx#2]
I might be missing it or this might be a future thing, but is it possible to Hold one button down and then click another for the outcome to trigger? 

I tried this below but I don't think its built in to the rest of the code. But it would be cool if this was added!

- action: BB_ACTION_SPEED_DOWN
  event: BB_EVENT_DPAD_DOWN
  event: BB_EVENT_BTN_START
  min: 0
  max: 1

**Comment by NerdsCorp** [comment]
this would make it so you could free up main buttons and have "config/tuning" in a different layer thus creating more advanced Projects using this.

**Comment by atctwo** [comment]
I think i might have an idea of how to do this.  What if each binding had an optional key called `conditionals` or something, which can either be an event or a list of events.  The binding's action is only executed if all of the conditional events resolve as true.  I think each event would be resolved by the same logic as boolean-input actions (like BB_ACTION_SPEED_DOWN), where it is `true` if the event value is greater than the halfway point between min and max.  Because the main event and conditional events might have different ranges, I'll also add a `conditional_min` (default=0) and `conditional_max` (default=1).

For example, if you wanted to have speed control stuff gated behind the start button (like in your post) you could do something like this:
```yaml
- action: BB_ACTION_SPEED_DOWN
  event: BB_EVENT_DPAD_DOWN
  conditionals: BB_EVENT_BTN_START
  min: 0
  max: 1
```

Another example, if you instead wanted to check that _both_ analog sticks are pushed upwards (ie: Y axis > 0), you could do
```yaml
- action: BB_ACTION_SPEED_DOWN
  event: BB_EVENT_DPAD_DOWN
  conditionals: [BB_EVENT_ANALOG_LY, BB_EVENT_ANALOG_RY]
  min: 0
  max: 1
  conditional_min: 0
  conditional_max: 511
```

At least I think this would work?  What do you think?
